name: Build macOS app
on: push
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip3 install pandas openpyxl py2app
      - run: python3 setup_mac.py py2app
      - uses: actions/upload-artifact@v4
        with:
          name: JDE_Конвертер
          path: dist/
